### ISSUE TITLE
Error in installing ilpyt

### ISSUE THREAD

**Issue by abheek19** [mitre/ilpyt#1]
When going through the installation process, after the command

`pip3 install ilpyt`

I am encountering the following error

> Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [1 lines of output]
>       error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

How do I solve this?

**Comment by atapley** [comment]
Hello, thanks for using ilpyt! I believe this issue is due to a change within OpenAI `gym` or `setuptools` where they do not work together due to versioning. You should be able to find the fix online - I believe `setuptools` should be set to version `65.5.0` according to [this issue](https://github.com/readthedocs/readthedocs.org/issues/10286).

This project is no longer being funded so we cannot update the repository to force the required version, but thank you for pointing it out!
